services:
  # 1. Service Aplikasi Node.js (Akan di-build oleh Jenkins)
  app:
    image: ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} # Variabel dari Jenkins
    container_name: todo-app
    restart: always
    ports:
      - "${HOST_PORT}:3000" # Mapping port publik ke port internal 3000
    depends_on:
      - db # Pastikan DB siap sebelum App dimulai
    environment:
      # Variabel lingkungan untuk koneksi ke kontainer 'db'
      DB_HOST: db
      DB_USER: user_todo
      DB_PASSWORD: supersecretpassword
      DB_NAME: todo_db
    networks:
      - app-network
    expose:
      - "3000" # Mengekspos port internal untuk komunikasi antar kontainer

  # 2. Service Database PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: user_todo
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: todo_db
    volumes:
      - db_data:/var/lib/postgresql/data # Volume untuk persistence data
    networks:
      - app-network

  # --- SERVICE BARU: PROMETHEUS ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro # Memuat file konfigurasi
      - prometheus-data:/prometheus # Volume untuk menyimpan data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.html=/usr/share/prometheus/console'
    ports:
      - "9090:9090" # Port Prometheus
    restart: always
    depends_on:
      - app

  # --- SERVICE BARU: GRAFANA ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # Grafana berjalan di port 3000 di kontainer, kita petakan ke 3001 di host
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
# Jaringan Internal Docker
networks:
  app-network:
    driver: bridge

# Volume untuk Menyimpan Data DB Permanen
volumes:
  db_data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
